// ===========================
// STUDENT SURVEY APP
// ===========================

// Survey Questions
const questions = [
    {
            question: "What is your age?",
                    answers: ["Under 18", "18–24", "25–34", "35+"]
                        },
                            {
                                    question: "What is your gender?",
                                            answers: ["Male", "Female", "Prefer not to say"]
                                                },
                                                    {
                                                            question: "Which year are you in?",
                                                                    answers: ["Year 1", "Year 2", "Year 3", "Year 4"]
                                                                        },
                                                                            {
                                                                                    question: "How satisfied are you with your lecturers?",
                                                                                            answers: [
                                                                                                        "Very Satisfied",
                                                                                                                    "Satisfied",
                                                                                                                                "Neutral",
                                                                                                                                            "Dissatisfied"
                                                                                                                                                    ]
                                                                                                                                                        },
                                                                                                                                                            {
                                                                                                                                                                    question: "Would you recommend this university?",
                                                                                                                                                                            answers: ["Yes", "No"]
                                                                                                                                                                                }
                                                                                                                                                                                ];

                                                                                                                                                                                // Variables
                                                                                                                                                                                let currentQuestion = 0;
                                                                                                                                                                                let userAnswers = [];

                                                                                                                                                                                // Get HTML Elements
                                                                                                                                                                                const questionElement = document.getElementById("question");
                                                                                                                                                                                const answersElement = document.getElementById("answers");
                                                                                                                                                                                const progressBar = document.getElementById("progressBar");
                                                                                                                                                                                const questionCounter = document.getElementById("questionCounter");
                                                                                                                                                                                const nextButton = document.getElementById("nextBtn");
                                                                                                                                                                                const previousButton = document.getElementById("prevBtn");

                                                                                                                                                                                // Only run on survey page
                                                                                                                                                                                if (questionElement) {

                                                                                                                                                                                    loadQuestion();

                                                                                                                                                                                        nextButton.addEventListener("click", nextQuestion);
                                                                                                                                                                                            previousButton.addEventListener("click", previousQuestion);

                                                                                                                                                                                            }

                                                                                                                                                                                            // ===========================
                                                                                                                                                                                            // Load Question
                                                                                                                                                                                            // ===========================

                                                                                                                                                                                            function loadQuestion() {

                                                                                                                                                                                                const current = questions[currentQuestion];

                                                                                                                                                                                                    questionElement.textContent = current.question;

                                                                                                                                                                                                        questionCounter.textContent =
                                                                                                                                                                                                                `Question ${currentQuestion + 1} of ${questions.length}`;

                                                                                                                                                                                                                    progressBar.style.width =
                                                                                                                                                                                                                            `${((currentQuestion + 1) / questions.length) * 100}%`;

                                                                                                                                                                                                                                answersElement.innerHTML = "";

                                                                                                                                                                                                                                    current.answers.forEach((answer, index) => {

                                                                                                                                                                                                                                            const card = document.createElement("div");

                                                                                                                                                                                                                                                    card.className = "answer-card";

                                                                                                                                                                                                                                                            card.textContent = answer;

                                                                                                                                                                                                                                                                    if (userAnswers[currentQuestion] === index) {
                                                                                                                                                                                                                                                                                card.classList.add("selected");
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                card.onclick = function () {

                                                                                                                                                                                                                                                                                                            document.querySelectorAll(".answer-card").forEach(card => {

                                                                                                                                                                                                                                                                                                                            card.classList.remove("selected");

                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                    this.classList.add("selected");

                                                                                                                                                                                                                                                                                                                                                                userAnswers[currentQuestion] = index;

                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                answersElement.appendChild(card);

                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                        previousButton.style.visibility =
                                                                                                                                                                                                                                                                                                                                                                                                currentQuestion === 0 ? "hidden" : "visible";

                                                                                                                                                                                                                                                                                                                                                                                                    nextButton.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                            currentQuestion === questions.length - 1
                                                                                                                                                                                                                                                                                                                                                                                                                        ? "Submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                    : "Next";

                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    // ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                    // Next Question
                                                                                                                                                                                                                                                                                                                                                                                                                                    // ===========================

                                                                                                                                                                                                                                                                                                                                                                                                                                    function nextQuestion() {

                                                                                                                                                                                                                                                                                                                                                                                                                                        if (userAnswers[currentQuestion] === undefined) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                alert("Please select an answer before continuing.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (currentQuestion < questions.length - 1) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currentQuestion++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loadQuestion();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showThankYou();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Previous Question
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ===========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function previousQuestion() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (currentQuestion > 0) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentQuestion--;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loadQuestion();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ===========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Thank You Screen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ===========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function showThankYou() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const surveyCard = document.querySelector(".survey-card");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                surveyCard.innerHTML = `

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="thank-you">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>✔ Thank You!</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Your response has been submitted successfully.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                We appreciate your participation.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }